# Generated by Django 2.1.15 on 2020-05-11 16:57

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_auto_20200114_0708'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chat room', max_length=200)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
                ('dp', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(default='N/A', max_length=200)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
                ('admins', models.ManyToManyField(related_name='admin', to='MMSApp.CustomUser')),
                ('members', models.ManyToManyField(related_name='member', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agenda', models.CharField(max_length=500)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True)),
                ('end_time', models.DateTimeField(blank=True)),
                ('duration', models.IntegerField(default=1)),
                ('venue', models.CharField(default='N/A', max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
                ('attendees', models.ManyToManyField(related_name='attendee', to='MMSApp.CustomUser')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.ChatRoom')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=300)),
                ('isRead', models.BooleanField(default=False)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
                ('target_users', models.ManyToManyField(related_name='notif', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfile', models.FileField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.CharField(default='', editable=False, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='resources',
            field=models.ManyToManyField(to='MMSApp.Resource'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='events',
            field=models.ManyToManyField(to='MMSApp.Event'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule_users', to='MMSApp.DailySchedule'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(to='MMSApp.Message'),
        ),
    ]
