# Generated by Django 2.0 on 2020-05-11 05:26

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Chat room', max_length=200)),
                ('uuid', models.CharField(default='06da348b-0d34-40fd-91f5-0202ec58249a', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uuid', models.CharField(default='34cfa93b-8a26-4088-8c6c-71569bc99ba0', editable=False, max_length=100)),
                ('dp', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('uuid', models.CharField(default='e1f35f30-978a-4e84-b1cd-ce3b30a636a3', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=200)),
                ('venue', models.CharField(default='N/A', max_length=200)),
                ('uuid', models.CharField(default='ea68273b-97d4-457a-a0d4-0c34403db9b3', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='75ef4bc8-b07f-4dfd-89f4-ed3306aea1bc', editable=False, max_length=100)),
                ('admins', models.ManyToManyField(related_name='admin', to='MMSApp.CustomUser')),
                ('members', models.ManyToManyField(related_name='member', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agenda', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('venue', models.CharField(default='N/A', max_length=200)),
                ('created_date', models.DateTimeField()),
                ('uuid', models.CharField(default='2a53522c-170f-4af6-af19-5be0d6a4cf7c', editable=False, max_length=100)),
                ('attendees', models.ManyToManyField(related_name='attendee', to='MMSApp.CustomUser')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.ChatRoom')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='143cddec-dded-416e-ba2b-9fba4bad8a07', editable=False, max_length=100)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=300)),
                ('isRead', models.BooleanField(default=False)),
                ('uuid', models.CharField(default='24f52ee5-5dd6-421c-8d76-cfd2232eb083', editable=False, max_length=100)),
                ('target_users', models.ManyToManyField(related_name='notif', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfile', models.FileField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(default='1813608c-9645-495c-abf8-7ded686d8a9f', editable=False, max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uuid', models.CharField(default='a8cf95ce-3624-4bc2-a205-e04a42cc56be', editable=False, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='resources',
            field=models.ManyToManyField(to='MMSApp.Resource'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='events',
            field=models.ManyToManyField(to='MMSApp.Event'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='schedule',
            field=models.ManyToManyField(related_name='schedule_users', to='MMSApp.DailySchedule'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(to='MMSApp.Message'),
        ),
    ]
