# Generated by Django 2.0 on 2020-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dp',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
