# Generated by Django 2.0 on 2020-04-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MMSApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField()),
                ('admins', models.ManyToManyField(related_name='admin', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('agenda', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('admin', models.ManyToManyField(related_name='meeting_admin', to='MMSApp.CustomUser')),
                ('attendees', models.ManyToManyField(related_name='attendee', to='MMSApp.CustomUser')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.ChatRoom')),
                ('invitees', models.ManyToManyField(related_name='invitee', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=300)),
                ('target_users', models.ManyToManyField(related_name='notif', to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfile', models.FileField(upload_to='')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_schedules', models.ManyToManyField(to='MMSApp.DailySchedule')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='resources',
            field=models.ManyToManyField(to='MMSApp.Resource'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.Venue'),
        ),
        migrations.AddField(
            model_name='group',
            name='meetings',
            field=models.ManyToManyField(related_name='group', to='MMSApp.Meeting'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='member', to='MMSApp.CustomUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='Venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MMSApp.Venue'),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='events',
            field=models.ManyToManyField(to='MMSApp.Event'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='messages',
            field=models.ManyToManyField(to='MMSApp.Message'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='schedule',
            field=models.ManyToManyField(to='MMSApp.Schedule'),
        ),
    ]
