# Generated by Django 2.1.15 on 2020-04-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSApp', '0002_auto_20200428_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='admin',
            new_name='admins',
        ),
        migrations.AddField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
