# Generated by Django 2.1.15 on 2020-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMSApp', '0002_customuser_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dp',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
